name: crypto_wallet
description: "Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  translator: ^1.0.3+1
  dio: ^5.8.0+1
  intl: ^0.20.2
  fl_chart: ^1.0.0
  provider: ^6.1.5
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  firebase_core: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/crypto_wallet_icon_splash.png
    - assets/images/crypto_default_icon_image.jpg
    - assets/images/crypto_wallet_icon_welcome.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

flutter_native_splash:
  color: "#000000"
  image: assets/images/crypto_wallet_icon_splash.png

  android_12:
    image: assets/images/crypto_wallet_icon_splash.png
    icon_background_color: "#000000"
    color: "#000000"

  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center