name: crypto_wallet
description: "Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  dio: ^5.8.0+1
  provider: ^6.1.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/logo.png
    - assets/images/graph.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#000000"
    color: "#000000"

  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center